// ─── BULK SEED: 500 unique topics queued for generation ───
// Run once: node scripts/bulk-seed.mjs
// Creates 500 article stubs with status: "queued" in content/articles/
// The cron worker will generate and publish them over time.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const contentDir = path.join(__dirname, '..', 'content', 'articles');

const CATEGORIES = [
  { slug: 'the-science', name: 'The Science' },
  { slug: 'the-microdose', name: 'The Microdose' },
  { slug: 'the-journey', name: 'The Journey' },
  { slug: 'the-clinic', name: 'The Clinic' },
  { slug: 'the-integration', name: 'The Integration' },
];

function slugify(title) {
  return title.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);
}

// ─── 500 UNIQUE TOPICS ───
// Organized by category (100 per category)
const SEED_TOPICS = [
  // ═══ THE SCIENCE (100) ═══
  { cat: 0, title: 'How Psilocybin Affects Serotonin 2A Receptors in the Prefrontal Cortex' },
  { cat: 0, title: 'The Neuroscience of Ego Dissolution During Psychedelic Experiences' },
  { cat: 0, title: 'fMRI Studies Showing Brain Connectivity Changes After a Single Psilocybin Dose' },
  { cat: 0, title: 'Why Psychedelics Increase Neuroplasticity and What That Means for Healing' },
  { cat: 0, title: 'The Entropic Brain Hypothesis and How Psychedelics Expand Consciousness' },
  { cat: 0, title: 'Comparing Psilocybin and SSRIs for Treatment-Resistant Depression' },
  { cat: 0, title: 'How Microdosing Affects BDNF and Nerve Growth Factor Production' },
  { cat: 0, title: 'The Role of the Claustrum in Psychedelic-Induced Altered States' },
  { cat: 0, title: 'Psychedelic Research at Johns Hopkins: Key Findings from 2020 to 2026' },
  { cat: 0, title: 'How Psilocybin Reduces Amygdala Reactivity in Anxiety Patients' },
  { cat: 0, title: 'The Gut-Brain Axis and How Mushrooms Influence Mental Health Through Digestion' },
  { cat: 0, title: 'Understanding Tryptamine Pharmacology and Why Psilocin Matters' },
  { cat: 0, title: 'How Psychedelics Disrupt Rumination Loops in Depression' },
  { cat: 0, title: 'The Science Behind Mystical Experiences and Their Therapeutic Value' },
  { cat: 0, title: 'Genetic Factors That Influence Individual Responses to Psilocybin' },
  { cat: 0, title: 'How Long Do Neuroplasticity Windows Stay Open After a Psychedelic Session' },
  { cat: 0, title: 'The Relationship Between Inflammation and Depression: Where Mushrooms Fit' },
  { cat: 0, title: 'Understanding Cross-Tolerance Between Different Psychedelic Compounds' },
  { cat: 0, title: 'How Psilocybin Changes Default Mode Network Activity in Real Time' },
  { cat: 0, title: 'The Science of Afterglow: Why You Feel Better for Weeks After a Trip' },
  { cat: 0, title: 'Comparing Natural Psilocybin to Synthetic Psilocybin in Clinical Trials' },
  { cat: 0, title: 'How Psychedelics Affect Memory Reconsolidation in PTSD Treatment' },
  { cat: 0, title: 'The Role of Oxytocin Release During Psychedelic Experiences' },
  { cat: 0, title: 'Why Some People Are More Sensitive to Psychedelics Than Others' },
  { cat: 0, title: 'The Neuroscience of Emotional Breakthrough During Psilocybin Therapy' },
  { cat: 0, title: 'How Beta-Glucans in Medicinal Mushrooms Support Immune Function' },
  { cat: 0, title: 'The Science of Synesthesia During Psychedelic States' },
  { cat: 0, title: 'Understanding Receptor Downregulation and Psychedelic Tolerance' },
  { cat: 0, title: 'How Psilocybin Therapy Compares to CBT for Social Anxiety' },
  { cat: 0, title: 'The Pharmacokinetics of Psilocybin: Absorption, Metabolism, and Duration' },
  { cat: 0, title: 'How Psychedelics Affect the Anterior Cingulate Cortex and Decision Making' },
  { cat: 0, title: 'The Science of Microdosing: What Double-Blind Studies Actually Show' },
  { cat: 0, title: 'How Functional Mushrooms Differ from Psychoactive Mushrooms at the Molecular Level' },
  { cat: 0, title: 'The Relationship Between Psychedelic Experiences and Long-Term Personality Change' },
  { cat: 0, title: 'How Psilocybin Affects Sleep Architecture and REM Cycles' },
  { cat: 0, title: 'The Neuroscience of Awe and Why Psychedelics Reliably Produce It' },
  { cat: 0, title: 'Understanding MAO Inhibitors and Their Role in Ayahuasca Pharmacology' },
  { cat: 0, title: 'How Psychedelics Reduce Activity in the Posterior Cingulate Cortex' },
  { cat: 0, title: 'The Science Behind Music-Enhanced Psychedelic Therapy Sessions' },
  { cat: 0, title: 'How Reishi Mushroom Triterpenes Affect Cortisol and Stress Response' },
  { cat: 0, title: 'The Neurobiology of Addiction and How Psilocybin Disrupts Habitual Patterns' },
  { cat: 0, title: 'How Psychedelics Increase Functional Connectivity Between Brain Regions' },
  { cat: 0, title: 'The Science of Dosage: Why Milligrams Per Kilogram Matters' },
  { cat: 0, title: 'How Lions Mane Stimulates Nerve Growth Factor in Human Studies' },
  { cat: 0, title: 'The Relationship Between Psychedelic Intensity and Therapeutic Outcome' },
  { cat: 0, title: 'How Cordyceps Affects Cellular ATP Production and Physical Performance' },
  { cat: 0, title: 'The Science of Psychedelic-Assisted Therapy for End-of-Life Anxiety' },
  { cat: 0, title: 'How Turkey Tail Polysaccharides Support Gut Microbiome Diversity' },
  { cat: 0, title: 'The Neuroscience of Crying During Psychedelic Sessions and Why It Heals' },
  { cat: 0, title: 'How Chaga Mushroom Antioxidants Compare to Other Superfoods' },
  { cat: 0, title: 'The Science of Psychedelic Microdosing for ADHD Symptom Management' },
  { cat: 0, title: 'How Maitake D-Fraction Supports Blood Sugar Regulation' },
  { cat: 0, title: 'The Neuroscience of Gratitude and How Psychedelics Amplify It' },
  { cat: 0, title: 'How Shiitake Lentinan Supports Cardiovascular Health' },
  { cat: 0, title: 'The Science of Psychedelic Peak Experiences and Their Lasting Impact' },
  { cat: 0, title: 'How Tremella Mushroom Supports Skin Hydration at the Cellular Level' },
  { cat: 0, title: 'The Neuroscience of Forgiveness and How Psychedelics Facilitate It' },
  { cat: 0, title: 'How Agarikon Mushroom Shows Promise as an Antiviral Agent' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Obsessive-Compulsive Disorder' },
  { cat: 0, title: 'How Meshima Mushroom Supports Hormonal Balance in Women' },
  { cat: 0, title: 'The Neuroscience of Self-Compassion and Psychedelic-Induced Perspective Shifts' },
  { cat: 0, title: 'How Royal Sun Mushroom Supports Blood Pressure Regulation' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Eating Disorders' },
  { cat: 0, title: 'How Enoki Mushroom Compounds Show Anti-Cancer Properties in Lab Studies' },
  { cat: 0, title: 'The Neuroscience of Flow States and Their Connection to Microdosing' },
  { cat: 0, title: 'How Oyster Mushroom Lovastatin Naturally Supports Cholesterol Levels' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Chronic Pain Conditions' },
  { cat: 0, title: 'How Psilocybin Affects the Thalamic Filter and Sensory Processing' },
  { cat: 0, title: 'The Neuroscience of Creativity and How Psychedelics Open New Neural Pathways' },
  { cat: 0, title: 'How Medicinal Mushroom Polysaccharides Train the Innate Immune System' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Moral Injury in Veterans' },
  { cat: 0, title: 'How Psilocybin Affects Heart Rate Variability and Autonomic Nervous System' },
  { cat: 0, title: 'The Neuroscience of Trust and How Psychedelics Rebuild It After Trauma' },
  { cat: 0, title: 'How Mushroom Chitin Supports Prebiotic Gut Health' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Fibromyalgia and Chronic Fatigue' },
  { cat: 0, title: 'How Psilocybin Microdosing Affects Divergent Thinking in Controlled Studies' },
  { cat: 0, title: 'The Neuroscience of Acceptance and How Psychedelics Reduce Resistance' },
  { cat: 0, title: 'How Adaptogenic Mushrooms Help Regulate the HPA Axis' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Alcohol Use Disorder' },
  { cat: 0, title: 'How Psilocybin Affects Glutamate Signaling in the Prefrontal Cortex' },
  { cat: 0, title: 'The Neuroscience of Meaning-Making and How Psychedelics Enhance It' },
  { cat: 0, title: 'How Functional Mushroom Blends Create Synergistic Health Effects' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Smoking Cessation' },
  { cat: 0, title: 'How Psilocybin Affects Theta Brain Wave Activity During Meditation' },
  { cat: 0, title: 'The Neuroscience of Embodiment and Why Psychedelics Help You Feel Your Body' },
  { cat: 0, title: 'How Mushroom Ergothioneine Acts as a Cellular Longevity Antioxidant' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Cluster Headaches' },
  { cat: 0, title: 'How Psilocybin Affects the Insula and Interoceptive Awareness' },
  { cat: 0, title: 'The Neuroscience of Wonder and How Psychedelics Restore Childlike Curiosity' },
  { cat: 0, title: 'How Medicinal Mushrooms Support Mitochondrial Function and Energy' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Grief and Bereavement' },
  { cat: 0, title: 'How Psilocybin Affects Dopamine Pathways Differently Than Stimulants' },
  { cat: 0, title: 'The Neuroscience of Interconnection and Why Psychedelics Reduce Loneliness' },
  { cat: 0, title: 'How Mushroom Beta-Glucans Prime Natural Killer Cell Activity' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Anorexia Nervosa' },
  { cat: 0, title: 'How Psilocybin Affects the Hippocampus and Emotional Memory Processing' },
  { cat: 0, title: 'The Neuroscience of Surrender and Why Letting Go Matters in Psychedelic Work' },
  { cat: 0, title: 'How Dual-Extract Mushroom Tinctures Maximize Bioavailability' },
  { cat: 0, title: 'The Science of Psychedelic Therapy for Tinnitus and Phantom Sensations' },
  { cat: 0, title: 'How Psilocybin Affects the Locus Coeruleus and Norepinephrine Release' },
  { cat: 0, title: 'The Neuroscience of Presence and How Psychedelics Anchor You in the Now' },

  // ═══ THE MICRODOSE (100) ═══
  { cat: 1, title: 'The Fadiman Protocol Explained: Every Third Day Microdosing Schedule' },
  { cat: 1, title: 'The Stamets Stack: Combining Psilocybin with Lions Mane and Niacin' },
  { cat: 1, title: 'Intuitive Microdosing: Listening to Your Body Instead of Following a Calendar' },
  { cat: 1, title: 'How to Prepare Consistent Microdose Capsules at Home' },
  { cat: 1, title: 'Microdosing for Focus: What to Expect in the First Two Weeks' },
  { cat: 1, title: 'The Difference Between Sub-Perceptual and Low-Dose Experiences' },
  { cat: 1, title: 'How to Track Your Microdosing Results with a Simple Journal System' },
  { cat: 1, title: 'Microdosing and Exercise: How Small Doses Enhance Physical Performance' },
  { cat: 1, title: 'The Best Time of Day to Take Your Microdose and Why It Matters' },
  { cat: 1, title: 'Microdosing Tolerance: When to Take Breaks and How Long' },
  { cat: 1, title: 'How Microdosing Affects Your Meditation Practice Over Time' },
  { cat: 1, title: 'Microdosing for Creative Professionals: Writers, Artists, and Musicians' },
  { cat: 1, title: 'The Relationship Between Microdosing and Improved Sleep Quality' },
  { cat: 1, title: 'How to Know If Your Microdose Is Too High or Too Low' },
  { cat: 1, title: 'Microdosing and Relationships: How Small Doses Affect Empathy and Connection' },
  { cat: 1, title: 'The Role of Intention Setting in Successful Microdosing Protocols' },
  { cat: 1, title: 'Microdosing for Programmers and Technical Problem Solving' },
  { cat: 1, title: 'How to Source Quality Psilocybin Mushrooms for Microdosing Safely' },
  { cat: 1, title: 'Microdosing and Anxiety: Why Some People Feel Worse Before Better' },
  { cat: 1, title: 'The Four-Day Protocol: An Alternative to Fadiman for Sensitive People' },
  { cat: 1, title: 'How Microdosing Affects Emotional Regulation Over a 30-Day Period' },
  { cat: 1, title: 'Microdosing with Functional Mushroom Stacks for Cognitive Enhancement' },
  { cat: 1, title: 'The Difference Between Microdosing Psilocybin and Microdosing LSD' },
  { cat: 1, title: 'How to Build a Morning Routine Around Your Microdosing Practice' },
  { cat: 1, title: 'Microdosing for Parents: Managing Family Life While Exploring Consciousness' },
  { cat: 1, title: 'The Role of Diet and Nutrition in Optimizing Your Microdose Response' },
  { cat: 1, title: 'Microdosing and Journaling: The Combination That Accelerates Growth' },
  { cat: 1, title: 'How to Transition from Microdosing to a Full Ceremonial Dose' },
  { cat: 1, title: 'Microdosing for Entrepreneurs: Creativity, Focus, and Decision Making' },
  { cat: 1, title: 'The Science of Stacking: Combining Microdoses with Adaptogens' },
  { cat: 1, title: 'How Microdosing Affects Your Relationship with Technology and Screens' },
  { cat: 1, title: 'Microdosing and Nature: Why Outdoor Time Amplifies the Benefits' },
  { cat: 1, title: 'The Difference Between Microdosing for Performance and Microdosing for Healing' },
  { cat: 1, title: 'How to Explain Your Microdosing Practice to Skeptical Family Members' },
  { cat: 1, title: 'Microdosing and Breathwork: A Powerful Daily Combination' },
  { cat: 1, title: 'The Role of Community in Sustaining a Long-Term Microdosing Practice' },
  { cat: 1, title: 'How Microdosing Affects Procrastination and Task Initiation' },
  { cat: 1, title: 'Microdosing for Teachers and Educators: Patience, Presence, and Creativity' },
  { cat: 1, title: 'The Relationship Between Microdosing and Reduced Caffeine Dependence' },
  { cat: 1, title: 'How to Use Microdosing as a Bridge to Deeper Therapeutic Work' },
  { cat: 1, title: 'Microdosing and Cold Exposure: Stacking Practices for Resilience' },
  { cat: 1, title: 'The Role of Expectation and Placebo in Microdosing Outcomes' },
  { cat: 1, title: 'How Microdosing Affects Pattern Recognition and Systems Thinking' },
  { cat: 1, title: 'Microdosing for Musicians: How Small Doses Affect Rhythm and Improvisation' },
  { cat: 1, title: 'The Difference Between Fresh and Dried Mushrooms for Microdosing' },
  { cat: 1, title: 'How to Create a Microdosing Accountability Partnership' },
  { cat: 1, title: 'Microdosing and Yoga: How Psilocybin Deepens Body Awareness' },
  { cat: 1, title: 'The Role of Rest Days in Preventing Microdosing Burnout' },
  { cat: 1, title: 'How Microdosing Affects Your Sense of Humor and Playfulness' },
  { cat: 1, title: 'Microdosing for Healthcare Workers: Managing Compassion Fatigue' },
  { cat: 1, title: 'The Relationship Between Microdosing and Improved Emotional Vocabulary' },
  { cat: 1, title: 'How to Adjust Your Microdose During Seasonal Changes' },
  { cat: 1, title: 'Microdosing and Somatic Therapy: Combining Bottom-Up Approaches' },
  { cat: 1, title: 'The Role of Gratitude Practice in Amplifying Microdose Benefits' },
  { cat: 1, title: 'How Microdosing Affects Your Relationship with Food and Eating' },
  { cat: 1, title: 'Microdosing for Therapists: Using Personal Experience to Inform Practice' },
  { cat: 1, title: 'The Difference Between Microdosing Cubensis and Microdosing Truffles' },
  { cat: 1, title: 'How to Navigate Microdosing When You Take Pharmaceutical Medications' },
  { cat: 1, title: 'Microdosing and Flow States: The Optimal Dose for Peak Performance' },
  { cat: 1, title: 'The Role of Moon Cycles in Timing Your Microdosing Protocol' },
  { cat: 1, title: 'How Microdosing Affects Your Dreams and Subconscious Processing' },
  { cat: 1, title: 'Microdosing for Grief: Gentle Support During Loss and Transition' },
  { cat: 1, title: 'The Science of Microdosing Tolerance Reset: How Long Is Long Enough' },
  { cat: 1, title: 'How to Combine Microdosing with Talk Therapy for Deeper Insights' },
  { cat: 1, title: 'Microdosing and Aging: How Older Adults Are Finding Cognitive Benefits' },
  { cat: 1, title: 'The Role of Body Weight in Determining Your Ideal Microdose' },
  { cat: 1, title: 'How Microdosing Affects Social Anxiety in Professional Settings' },
  { cat: 1, title: 'Microdosing for Athletes: Recovery, Focus, and Mind-Body Connection' },
  { cat: 1, title: 'The Difference Between Microdosing for Maintenance and Microdosing for Change' },
  { cat: 1, title: 'How to End a Microdosing Protocol Gracefully and Integrate the Lessons' },
  { cat: 1, title: 'Microdosing and Attachment Style: How Small Doses Affect Relating Patterns' },
  { cat: 1, title: 'The Role of Surrender in Getting the Most from Your Microdosing Practice' },
  { cat: 1, title: 'How Microdosing Affects Your Capacity for Boredom and Stillness' },
  { cat: 1, title: 'Microdosing for Students: Academic Performance and Exam Preparation' },
  { cat: 1, title: 'The Relationship Between Microdosing and Reduced Alcohol Consumption' },
  { cat: 1, title: 'How to Microdose Responsibly While Maintaining Professional Obligations' },
  { cat: 1, title: 'Microdosing and Shadow Work: How Small Doses Surface Hidden Material' },
  { cat: 1, title: 'The Role of Physical Movement on Microdose Days' },
  { cat: 1, title: 'How Microdosing Affects Your Relationship with Money and Abundance' },
  { cat: 1, title: 'Microdosing for Chronic Pain: What the Anecdotal Evidence Shows' },
  { cat: 1, title: 'The Difference Between Microdosing Alone and Microdosing in Community' },
  { cat: 1, title: 'How to Build Resilience Through a Consistent Microdosing Practice' },
  { cat: 1, title: 'Microdosing and Digital Detox: Why Less Screen Time Amplifies Benefits' },
  { cat: 1, title: 'The Role of Hydration and Electrolytes in Microdosing Comfort' },
  { cat: 1, title: 'How Microdosing Affects Your Capacity for Difficult Conversations' },
  { cat: 1, title: 'Microdosing for Menopause: How Women Are Finding Hormonal Support' },
  { cat: 1, title: 'The Science of Microdosing and Neurogenesis in the Adult Brain' },
  { cat: 1, title: 'How to Create Sacred Space for Your Microdosing Practice at Home' },
  { cat: 1, title: 'Microdosing and Minimalism: How Less Becomes More Under the Influence' },
  { cat: 1, title: 'The Role of Silence and Solitude in Maximizing Microdose Insights' },
  { cat: 1, title: 'How Microdosing Affects Your Relationship with Anger and Boundaries' },
  { cat: 1, title: 'Microdosing for Seasonal Affective Disorder: A Winter Protocol' },
  { cat: 1, title: 'The Difference Between Taking a Microdose and Being on a Microdose' },
  { cat: 1, title: 'How to Recognize When Microdosing Has Done Its Work and You Can Stop' },
  { cat: 1, title: 'Microdosing and Couples Therapy: How Partners Can Explore Together' },
  { cat: 1, title: 'The Role of Fasting Before Your Microdose and Why Timing Matters' },
  { cat: 1, title: 'How Microdosing Affects Your Relationship with Nature and the Earth' },
  { cat: 1, title: 'Microdosing for Veterans: Addressing Service-Related Trauma Gently' },
  { cat: 1, title: 'The Science of Microdosing and Improved Emotional Granularity' },
  { cat: 1, title: 'How to Document Your Microdosing Journey for Future Reference' },

  // ═══ THE JOURNEY (100) ═══
  { cat: 2, title: 'Preparing for Your First Psilocybin Ceremony: A Complete Guide' },
  { cat: 2, title: 'The Art of Surrender: How to Let Go During a Psychedelic Experience' },
  { cat: 2, title: 'What to Do When Fear Arises During a Psychedelic Journey' },
  { cat: 2, title: 'Creating a Safe Physical Space for Your Psychedelic Experience' },
  { cat: 2, title: 'The Role of Music in Shaping Your Psychedelic Journey' },
  { cat: 2, title: 'How to Choose a Psychedelic Guide or Sitter You Can Trust' },
  { cat: 2, title: 'Understanding Dosage Levels: From Museum Dose to Heroic Dose' },
  { cat: 2, title: 'The Importance of Intention Setting Before a Psychedelic Experience' },
  { cat: 2, title: 'What Ego Death Actually Feels Like and Why It Can Be Healing' },
  { cat: 2, title: 'How to Navigate Difficult Emotions During a Psilocybin Journey' },
  { cat: 2, title: 'The Difference Between Recreational Use and Intentional Ceremony' },
  { cat: 2, title: 'How to Prepare Your Body in the Days Before a Psychedelic Experience' },
  { cat: 2, title: 'Understanding the Phases of a Psilocybin Journey from Onset to Return' },
  { cat: 2, title: 'The Role of Breathwork During Peak Psychedelic Experiences' },
  { cat: 2, title: 'How to Work with Nausea During the Come-Up Phase' },
  { cat: 2, title: 'The Power of Nature Settings for Outdoor Psychedelic Journeys' },
  { cat: 2, title: 'How to Support Someone Through a Challenging Psychedelic Experience' },
  { cat: 2, title: 'The Role of Silence Versus Conversation During Group Ceremonies' },
  { cat: 2, title: 'What to Expect in the First Hour After Taking Psilocybin Mushrooms' },
  { cat: 2, title: 'How to Work with Recurring Visions and Symbolic Content' },
  { cat: 2, title: 'The Difference Between Solo Journeys and Guided Ceremonies' },
  { cat: 2, title: 'How to Create a Psychedelic Playlist That Supports Deep Work' },
  { cat: 2, title: 'Understanding Body Load and Physical Sensations During Psychedelic Trips' },
  { cat: 2, title: 'The Role of Eye Masks in Deepening the Psychedelic Experience' },
  { cat: 2, title: 'How to Navigate Time Distortion During a Psilocybin Journey' },
  { cat: 2, title: 'The Art of Coming Down: Transitioning from Peak to Afterglow' },
  { cat: 2, title: 'How to Work with Ancestral Material That Surfaces During Journeys' },
  { cat: 2, title: 'The Role of Touch and Physical Comfort During Psychedelic Experiences' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Have Trauma History' },
  { cat: 2, title: 'The Difference Between Lemon Tek and Traditional Mushroom Tea Preparation' },
  { cat: 2, title: 'How to Set Up Emergency Support Before a High-Dose Experience' },
  { cat: 2, title: 'The Role of Fasting Before a Psychedelic Ceremony' },
  { cat: 2, title: 'How to Work with Grief That Surfaces During Psychedelic Journeys' },
  { cat: 2, title: 'The Art of Asking Questions to Your Psychedelic Experience' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences with a Partner Present' },
  { cat: 2, title: 'The Role of Temperature and Physical Environment During Journeys' },
  { cat: 2, title: 'How to Work with Childhood Memories That Surface Under Psilocybin' },
  { cat: 2, title: 'The Difference Between Mushroom Species and Their Unique Journey Qualities' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Have Religious Background' },
  { cat: 2, title: 'The Role of Art and Creative Expression During the Come-Down Phase' },
  { cat: 2, title: 'How to Work with Forgiveness Themes During Psychedelic Journeys' },
  { cat: 2, title: 'The Art of Receiving Messages from Your Psychedelic Experience' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Live with Others' },
  { cat: 2, title: 'The Role of Water and Hydration During Long Psychedelic Sessions' },
  { cat: 2, title: 'How to Work with Body Shame That Surfaces During Psychedelic Journeys' },
  { cat: 2, title: 'The Difference Between Challenging and Bad Psychedelic Experiences' },
  { cat: 2, title: 'How to Navigate Your First Group Ceremony with Strangers' },
  { cat: 2, title: 'The Role of Journaling Immediately After a Psychedelic Experience' },
  { cat: 2, title: 'How to Work with Relationship Insights That Surface During Journeys' },
  { cat: 2, title: 'The Art of Gratitude Practice at the End of a Psychedelic Session' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Have Anxiety Disorders' },
  { cat: 2, title: 'The Role of Crystals and Sacred Objects During Ceremony' },
  { cat: 2, title: 'How to Work with Death Anxiety That Surfaces During Psychedelic Journeys' },
  { cat: 2, title: 'The Difference Between Indoor and Outdoor Psychedelic Settings' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Are a Control Person' },
  { cat: 2, title: 'The Role of Candles and Lighting in Creating Ceremony Space' },
  { cat: 2, title: 'How to Work with Shame and Self-Judgment During Psychedelic Journeys' },
  { cat: 2, title: 'The Art of Preparing Food for After Your Psychedelic Experience' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Are Highly Sensitive' },
  { cat: 2, title: 'The Role of Blankets and Comfort Objects During Psychedelic Sessions' },
  { cat: 2, title: 'How to Work with Anger That Surfaces During Psilocybin Journeys' },
  { cat: 2, title: 'The Difference Between Daytime and Nighttime Psychedelic Journeys' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences After Previous Bad Trips' },
  { cat: 2, title: 'The Role of Aromatherapy and Scent During Psychedelic Ceremonies' },
  { cat: 2, title: 'How to Work with Loneliness That Surfaces During Solo Journeys' },
  { cat: 2, title: 'The Art of Closing a Psychedelic Ceremony with Intention' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Are Neurodivergent' },
  { cat: 2, title: 'The Role of Pets and Animals During Home Psychedelic Sessions' },
  { cat: 2, title: 'How to Work with Perfectionism That Surfaces During Journeys' },
  { cat: 2, title: 'The Difference Between Psilocybin Tea and Eating Whole Mushrooms' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences in Your 50s and Beyond' },
  { cat: 2, title: 'The Role of Prayer and Invocation in Psychedelic Ceremony' },
  { cat: 2, title: 'How to Work with Career Dissatisfaction That Surfaces During Journeys' },
  { cat: 2, title: 'The Art of Holding Space for Yourself During Solo Psychedelic Work' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Have Chronic Illness' },
  { cat: 2, title: 'The Role of Movement and Dance During Psychedelic Experiences' },
  { cat: 2, title: 'How to Work with Parental Wounds That Surface Under Psilocybin' },
  { cat: 2, title: 'The Difference Between Heroic Doses and Moderate Therapeutic Doses' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When English Is Not Your First Language' },
  { cat: 2, title: 'The Role of Ceremony Closing Rituals in Marking the Transition Back' },
  { cat: 2, title: 'How to Work with Spiritual Emergency During Intense Psychedelic Experiences' },
  { cat: 2, title: 'The Art of Patience During the Onset Phase of a Psilocybin Journey' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Have Trust Issues' },
  { cat: 2, title: 'The Role of Singing and Vocalization During Psychedelic Ceremonies' },
  { cat: 2, title: 'How to Work with Sexual Trauma That Surfaces During Psychedelic Journeys' },
  { cat: 2, title: 'The Difference Between Psychedelic Retreats and Home Ceremonies' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Are Grieving a Loss' },
  { cat: 2, title: 'The Role of Darkness and Sensory Deprivation in Deep Psychedelic Work' },
  { cat: 2, title: 'How to Work with Existential Questions That Arise During Journeys' },
  { cat: 2, title: 'The Art of Returning to Ordinary Consciousness After Deep Experiences' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Have Bipolar Tendencies' },
  { cat: 2, title: 'The Role of Ceremony Preparation Rituals in Building Container' },
  { cat: 2, title: 'How to Work with Joy and Ecstasy When They Arise During Journeys' },
  { cat: 2, title: 'The Difference Between Psychedelic Therapy and Psychedelic Recreation' },
  { cat: 2, title: 'How to Navigate Your Second or Third Psychedelic Experience Differently' },
  { cat: 2, title: 'The Role of Intention Cards and Written Prayers in Ceremony' },
  { cat: 2, title: 'How to Work with Resistance and Avoidance During Psychedelic Journeys' },
  { cat: 2, title: 'The Art of Being Present with Whatever Arises in Psychedelic Space' },
  { cat: 2, title: 'How to Navigate Psychedelic Experiences When You Are a Caregiver' },
  { cat: 2, title: 'The Role of Post-Journey Rest and Sleep in Processing the Experience' },

  // ═══ THE CLINIC (100) ═══
  { cat: 3, title: 'How to Find a Qualified Psychedelic Therapist in Your Area' },
  { cat: 3, title: 'What to Expect During Your First Ketamine-Assisted Therapy Session' },
  { cat: 3, title: 'The Difference Between Underground and Legal Psychedelic Therapy' },
  { cat: 3, title: 'How MDMA-Assisted Therapy Works for PTSD: The Clinical Protocol' },
  { cat: 3, title: 'Questions to Ask Before Choosing a Psychedelic Therapy Provider' },
  { cat: 3, title: 'The Role of Preparation Sessions in Clinical Psychedelic Therapy' },
  { cat: 3, title: 'How Insurance Coverage for Psychedelic Therapy Is Evolving' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Psychedelic Coaching' },
  { cat: 3, title: 'How to Evaluate the Safety Record of a Psychedelic Therapy Center' },
  { cat: 3, title: 'The Clinical Evidence for Psilocybin Therapy in Major Depression' },
  { cat: 3, title: 'How to Prepare for Your First Clinical Psilocybin Session' },
  { cat: 3, title: 'The Role of Integration Sessions After Clinical Psychedelic Therapy' },
  { cat: 3, title: 'How Psychedelic Therapy Differs from Traditional Talk Therapy' },
  { cat: 3, title: 'Understanding Contraindications: Who Should Not Do Psychedelic Therapy' },
  { cat: 3, title: 'The Cost of Psychedelic Therapy and How to Make It Accessible' },
  { cat: 3, title: 'How to Taper Off Antidepressants Safely Before Psychedelic Therapy' },
  { cat: 3, title: 'The Role of Medical Screening in Safe Psychedelic Therapy' },
  { cat: 3, title: 'How Group Psychedelic Therapy Sessions Work in Clinical Settings' },
  { cat: 3, title: 'Understanding the Legal Status of Psychedelic Therapy by State' },
  { cat: 3, title: 'How to Talk to Your Psychiatrist About Psychedelic Therapy Interest' },
  { cat: 3, title: 'The Difference Between Ketamine Infusions and Ketamine-Assisted Therapy' },
  { cat: 3, title: 'How Clinical Psychedelic Therapy Addresses Treatment-Resistant Conditions' },
  { cat: 3, title: 'The Role of the Therapeutic Alliance in Psychedelic Therapy Outcomes' },
  { cat: 3, title: 'How to Recognize Red Flags in Psychedelic Therapy Practitioners' },
  { cat: 3, title: 'Understanding Informed Consent in Psychedelic Therapy Settings' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Integrated into Palliative Care' },
  { cat: 3, title: 'The Role of Follow-Up Care After a Clinical Psychedelic Session' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Have a Complex Diagnosis' },
  { cat: 3, title: 'The Difference Between Psychedelic-Assisted Therapy and Psycholytic Therapy' },
  { cat: 3, title: 'How Clinical Trials for Psychedelic Therapy Work and How to Join' },
  { cat: 3, title: 'The Role of Therapist Training and Certification in Quality Care' },
  { cat: 3, title: 'How to Process Difficult Material That Emerges in Clinical Sessions' },
  { cat: 3, title: 'Understanding the Timeline: How Many Sessions Does Psychedelic Therapy Take' },
  { cat: 3, title: 'How Psychedelic Therapy Addresses Attachment Wounds and Relational Trauma' },
  { cat: 3, title: 'The Role of Somatic Experiencing in Psychedelic-Assisted Therapy' },
  { cat: 3, title: 'How to Maintain Progress Between Psychedelic Therapy Sessions' },
  { cat: 3, title: 'Understanding the Difference Between Harm Reduction and Clinical Therapy' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Used for Couples and Relationship Work' },
  { cat: 3, title: 'The Role of Peer Support in the Psychedelic Therapy Journey' },
  { cat: 3, title: 'How to Navigate Family Dynamics After Starting Psychedelic Therapy' },
  { cat: 3, title: 'Understanding the Ethics of Psychedelic Therapy: Boundaries and Power' },
  { cat: 3, title: 'How Psychedelic Therapy Is Evolving for Adolescent Mental Health' },
  { cat: 3, title: 'The Role of Nature-Based Settings in Clinical Psychedelic Work' },
  { cat: 3, title: 'How to Find Sliding Scale or Scholarship Psychedelic Therapy Options' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Spiritual Direction' },
  { cat: 3, title: 'How Psychedelic Therapy Addresses Perfectionism and High-Achiever Burnout' },
  { cat: 3, title: 'The Role of Art Therapy Techniques in Psychedelic Integration Work' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Are in Recovery from Addiction' },
  { cat: 3, title: 'Understanding the Research Pipeline: What New Psychedelic Therapies Are Coming' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Adapted for Indigenous Communities' },
  { cat: 3, title: 'The Role of Breathwork in Clinical Psychedelic Therapy Protocols' },
  { cat: 3, title: 'How to Prepare Your Support System Before Starting Psychedelic Therapy' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Shamanic Healing' },
  { cat: 3, title: 'How Psychedelic Therapy Addresses Chronic Shame and Self-Worth Issues' },
  { cat: 3, title: 'The Role of Music Therapy in Clinical Psychedelic Sessions' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Have a History of Psychosis' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Microdosing' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Used for Moral Injury in First Responders' },
  { cat: 3, title: 'The Role of Body-Based Interventions in Psychedelic Therapy' },
  { cat: 3, title: 'How to Choose Between Individual and Group Psychedelic Therapy' },
  { cat: 3, title: 'Understanding the Aftercare Protocol for Clinical Psychedelic Sessions' },
  { cat: 3, title: 'How Psychedelic Therapy Addresses Dissociation and Emotional Numbing' },
  { cat: 3, title: 'The Role of Mindfulness Training in Preparing for Psychedelic Therapy' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Are a Mental Health Professional' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Plant Medicine Ceremony' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Used for Autoimmune Conditions' },
  { cat: 3, title: 'The Role of Nutritional Support in Clinical Psychedelic Therapy' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Have Religious Concerns' },
  { cat: 3, title: 'Understanding the Training Requirements for Psychedelic Therapists' },
  { cat: 3, title: 'How Psychedelic Therapy Addresses Codependency and People-Pleasing' },
  { cat: 3, title: 'The Role of Movement and Embodiment in Psychedelic Therapy Sessions' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Are Neurodivergent' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Psychedelic Tourism' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Used for Existential Distress in Cancer' },
  { cat: 3, title: 'The Role of Dream Work in Psychedelic Therapy Integration' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Have Attachment Avoidance' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Holotropic Breathwork' },
  { cat: 3, title: 'How Psychedelic Therapy Addresses Burnout in Healthcare Workers' },
  { cat: 3, title: 'The Role of Journaling Protocols in Clinical Psychedelic Therapy' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Have Chronic Pain' },
  { cat: 3, title: 'Understanding the Emerging Field of Psychedelic Chaplaincy' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Used for Racial Trauma and Intergenerational Wounds' },
  { cat: 3, title: 'The Role of Consent and Autonomy in Psychedelic Therapy Ethics' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Are in a Leadership Role' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Ketamine Clinics' },
  { cat: 3, title: 'How Psychedelic Therapy Addresses Avoidant Personality Patterns' },
  { cat: 3, title: 'The Role of Community Integration Circles After Clinical Sessions' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Have a Partner Who Disagrees' },
  { cat: 3, title: 'Understanding the Long-Term Outcomes of Clinical Psychedelic Therapy' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Adapted for Elderly Populations' },
  { cat: 3, title: 'The Role of Trauma-Informed Care in Psychedelic Therapy Settings' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Have Complex PTSD' },
  { cat: 3, title: 'Understanding the Difference Between Psychedelic Therapy and Ibogaine Treatment' },
  { cat: 3, title: 'How Psychedelic Therapy Addresses Spiritual Bypassing and Avoidance' },
  { cat: 3, title: 'The Role of Cultural Sensitivity in Psychedelic Therapy Practice' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Work in Law Enforcement' },
  { cat: 3, title: 'Understanding the Emerging Standards for Psychedelic Therapy Facilities' },
  { cat: 3, title: 'How Psychedelic Therapy Is Being Used for Suicidal Ideation' },
  { cat: 3, title: 'The Role of Afterglow Optimization in Clinical Psychedelic Outcomes' },
  { cat: 3, title: 'How to Navigate Psychedelic Therapy When You Have a History of Self-Harm' },

  // ═══ THE INTEGRATION (100) ═══
  { cat: 4, title: 'The First 24 Hours After a Psychedelic Experience: What to Do and Avoid' },
  { cat: 4, title: 'How to Build a Daily Integration Practice After a Psilocybin Journey' },
  { cat: 4, title: 'The Role of Journaling in Processing Psychedelic Insights' },
  { cat: 4, title: 'How to Translate Psychedelic Visions into Concrete Life Changes' },
  { cat: 4, title: 'The Difference Between Integration and Spiritual Bypassing' },
  { cat: 4, title: 'How to Find an Integration Therapist or Coach After Your Experience' },
  { cat: 4, title: 'The Role of Community in Sustaining Psychedelic Integration' },
  { cat: 4, title: 'How to Navigate Relationship Changes After a Psychedelic Awakening' },
  { cat: 4, title: 'The Art of Slow Integration: Why Rushing Changes Backfires' },
  { cat: 4, title: 'How to Work with Psychedelic Insights That Challenge Your Current Life' },
  { cat: 4, title: 'The Role of Body-Based Practices in Psychedelic Integration' },
  { cat: 4, title: 'How to Integrate Difficult or Frightening Psychedelic Experiences' },
  { cat: 4, title: 'The Difference Between Integration and Interpretation of Psychedelic Content' },
  { cat: 4, title: 'How to Maintain Psychedelic Insights When You Return to Daily Routine' },
  { cat: 4, title: 'The Role of Nature Connection in Long-Term Psychedelic Integration' },
  { cat: 4, title: 'How to Navigate Career Changes Inspired by Psychedelic Experiences' },
  { cat: 4, title: 'The Art of Integration Circles: Finding and Joining a Community' },
  { cat: 4, title: 'How to Work with Grief That Continues After a Psychedelic Journey' },
  { cat: 4, title: 'The Role of Creative Expression in Processing Psychedelic Material' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences When You Cannot Talk About Them' },
  { cat: 4, title: 'The Difference Between Healthy Integration and Obsessive Processing' },
  { cat: 4, title: 'How to Navigate Spiritual Emergence After Intense Psychedelic Experiences' },
  { cat: 4, title: 'The Role of Meditation in Sustaining Psychedelic Awareness' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences with Your Existing Faith Tradition' },
  { cat: 4, title: 'The Art of Patience in Integration: Trusting the Unfolding Process' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Childhood and Family' },
  { cat: 4, title: 'The Role of Physical Exercise in Grounding After Psychedelic Experiences' },
  { cat: 4, title: 'How to Navigate Social Isolation After a Psychedelic Awakening' },
  { cat: 4, title: 'The Difference Between Integration Support and Traditional Therapy' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Felt Meaningless or Empty' },
  { cat: 4, title: 'The Role of Ritual and Ceremony in Ongoing Integration Practice' },
  { cat: 4, title: 'How to Navigate Identity Shifts After Psychedelic Experiences' },
  { cat: 4, title: 'The Art of Embodied Integration: Moving Insights from Head to Body' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Death and Mortality' },
  { cat: 4, title: 'The Role of Nutrition and Diet in Supporting Integration' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences When You Feel Overwhelmed' },
  { cat: 4, title: 'The Difference Between Integration and Trying to Recreate the Experience' },
  { cat: 4, title: 'How to Navigate Relationship Endings Inspired by Psychedelic Clarity' },
  { cat: 4, title: 'The Role of Sleep and Dreams in Processing Psychedelic Material' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Revealed Addiction Patterns' },
  { cat: 4, title: 'The Art of Gratitude Practice as an Integration Tool' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Purpose and Calling' },
  { cat: 4, title: 'The Role of Boundaries in Protecting Your Integration Process' },
  { cat: 4, title: 'How to Navigate Psychedelic Integration When Your Partner Did Not Journey' },
  { cat: 4, title: 'The Difference Between Integration and Avoidance of Difficult Material' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Opened Spiritual Channels' },
  { cat: 4, title: 'The Role of Forgiveness Practice in Psychedelic Integration' },
  { cat: 4, title: 'How to Navigate Work and Career During Active Integration Periods' },
  { cat: 4, title: 'The Art of Letting Go of Psychedelic Experiences That Did Not Meet Expectations' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Sexuality and Intimacy' },
  { cat: 4, title: 'The Role of Accountability Partners in Sustained Integration' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Surfaced Repressed Memories' },
  { cat: 4, title: 'The Difference Between Integration and Self-Improvement Obsession' },
  { cat: 4, title: 'How to Navigate Integration When You Feel You Have Changed Too Much' },
  { cat: 4, title: 'The Role of Music and Sound in Ongoing Integration Practice' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Money and Livelihood' },
  { cat: 4, title: 'The Art of Integration Through Service and Giving Back' },
  { cat: 4, title: 'How to Navigate Integration When You Feel Stuck or Stagnant' },
  { cat: 4, title: 'The Role of Reading and Study in Deepening Integration Understanding' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Challenged Your Worldview' },
  { cat: 4, title: 'The Difference Between Integration and Intellectualizing the Experience' },
  { cat: 4, title: 'How to Navigate Integration When You Want Another Journey Too Soon' },
  { cat: 4, title: 'The Role of Compassion Practice in Psychedelic Integration' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Aging and Time' },
  { cat: 4, title: 'The Art of Integration Through Simplifying Your Life' },
  { cat: 4, title: 'How to Navigate Integration When People Around You Do Not Understand' },
  { cat: 4, title: 'The Role of Somatic Release in Processing Stored Psychedelic Material' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Felt Like Past Lives' },
  { cat: 4, title: 'The Difference Between Integration and Denial of Difficult Truths' },
  { cat: 4, title: 'How to Navigate Integration When You Feel Called to Help Others' },
  { cat: 4, title: 'The Role of Humor and Lightness in Healthy Integration' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Creativity and Expression' },
  { cat: 4, title: 'The Art of Integration Through Honest Conversation' },
  { cat: 4, title: 'How to Navigate Integration When You Experience Spiritual Emergency' },
  { cat: 4, title: 'The Role of Time in Nature for Processing Psychedelic Experiences' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Revealed Shadow Material' },
  { cat: 4, title: 'The Difference Between Integration and Performing Transformation' },
  { cat: 4, title: 'How to Navigate Integration When You Feel More Sensitive Than Before' },
  { cat: 4, title: 'The Role of Breathwork in Ongoing Psychedelic Integration' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Belonging and Community' },
  { cat: 4, title: 'The Art of Integration Through Daily Micro-Practices' },
  { cat: 4, title: 'How to Navigate Integration When Old Patterns Try to Reassert Themselves' },
  { cat: 4, title: 'The Role of Therapy in Supporting Deep Psychedelic Integration' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Felt Cosmic or Universal' },
  { cat: 4, title: 'The Difference Between Integration and Spiritual Materialism' },
  { cat: 4, title: 'How to Navigate Integration When You Feel Disconnected from Your Old Self' },
  { cat: 4, title: 'The Role of Writing and Storytelling in Making Sense of Psychedelic Journeys' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Boundaries and Saying No' },
  { cat: 4, title: 'The Art of Integration Through Embodied Movement and Dance' },
  { cat: 4, title: 'How to Navigate Integration When You Feel Called to Change Everything at Once' },
  { cat: 4, title: 'The Role of Patience and Self-Compassion in the Integration Timeline' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences That Opened Your Heart Wider' },
  { cat: 4, title: 'The Difference Between Integration and Attachment to Peak Experiences' },
  { cat: 4, title: 'How to Navigate Integration When You Feel Both Grateful and Overwhelmed' },
  { cat: 4, title: 'The Role of Mentorship in Guiding Long-Term Psychedelic Integration' },
  { cat: 4, title: 'How to Work with Psychedelic Insights About Letting Go of Control' },
  { cat: 4, title: 'The Art of Integration as a Lifelong Practice Not a Destination' },
  { cat: 4, title: 'How to Navigate Integration When the Insights Keep Coming Weeks Later' },
  { cat: 4, title: 'The Role of Celebration and Joy in Marking Integration Milestones' },
  { cat: 4, title: 'How to Integrate Psychedelic Experiences Into Your Parenting' },
  { cat: 4, title: 'The Difference Between Integration and Trying to Be a Different Person' },
];

// ─── MAIN ───
async function main() {
  // Get existing slugs to avoid duplicates
  const existingFiles = fs.readdirSync(contentDir).filter(f => f.endsWith('.json'));
  const existingSlugs = new Set(existingFiles.map(f => f.replace('.json', '')));
  console.log(`[bulk-seed] Existing articles: ${existingSlugs.size}`);

  let seeded = 0;
  let skipped = 0;

  for (const topic of SEED_TOPICS) {
    const slug = slugify(topic.title);
    if (existingSlugs.has(slug)) {
      skipped++;
      continue;
    }

    const category = CATEGORIES[topic.cat];
    const article = {
      slug,
      title: topic.title,
      categorySlug: category.slug,
      categoryName: category.name,
      dateISO: new Date().toISOString(),
      body: '', // empty — will be generated by cron
      excerpt: '',
      heroImage: '',
      ogImage: '',
      heroAlt: `Illustration for ${topic.title}`,
      readingTime: 0,
      status: 'queued',
      queued_at: new Date().toISOString(),
      published_at: null,
      publishDate: null,
      wordCount: 0,
    };

    fs.writeFileSync(path.join(contentDir, `${slug}.json`), JSON.stringify(article, null, 2));
    seeded++;
  }

  console.log(`[bulk-seed] Seeded: ${seeded} | Skipped (already exist): ${skipped}`);
  console.log(`[bulk-seed] Total articles now: ${existingSlugs.size + seeded}`);
  console.log(`[bulk-seed] Queue ready for cron generation.`);
}

main().catch(err => {
  console.error('[bulk-seed] Fatal:', err);
  process.exit(1);
});
